[style.description]
foreground = { rgb = [252, 252, 250] }  # Monokai Pro Spectrum foreground
underline = false
bold = false
italic = false

[style.command_name]
foreground = { rgb = [252, 145, 88] }   # Monokai Pro Spectrum orange
underline = false
bold = true
italic = false

[style.example_text]
foreground = { rgb = [191, 199, 213] }  # Monokai Pro Spectrum comment gray
underline = false
bold = false
italic = false

[style.example_code]
foreground = { rgb = [120, 220, 232] }  # Monokai Pro Spectrum cyan
underline = false
bold = true
italic = false

[style.example_variable]
foreground = { rgb = [255, 97, 136] }   # Monokai Pro Spectrum pink
underline = true
bold = false
italic = false

[display]
compact = false
use_pager = false
show_title = false

[updates]
auto_update = true
auto_update_interval_hours = 720
archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/"
tls_backend = "rustls-with-webpki-roots"

[directories]

[search]
